import { Description, Section, Title, Text } from "./About.styled";

const About = () => {
	return (
		<Section>
			<Title>
				a Story that started with <span>one simple ape</span>
			</Title>
			<Description>
				Who got fed up with boring and hypocritic commonplace this is how the
				idea of escaping and dynamic journey on the yacht
			</Description>
			<div>X</div>
			<Text>
				Each artwork in the collection tells a story of one journey. Arts are
				Randomly generated by users
			</Text>
			<div>...Have no limits...</div>
		</Section>
	);
};

export { About };
