const About = () => {
	return (
		<section>
			<h2>a Story that started with one simple ape</h2>
			<p>
				WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
				IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
			</p>
			<div>X</div>
			<p>
				EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
				RANDOMLY GENERATED BY USERS
			</p>
			<div>...HAVE NO LIMITS...</div>
		</section>
	);
};

export { About };
